version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./project_dir:/project_dir
    ports:
      - "8000:8000"
    depends_on:
      - db

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "7815:7815"
    env_file:
      - .env
    volumes:
      - ./project_dir:/project_dir
    depends_on:
      - api

volumes:
  postgres_data:
